version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ${CLIENT_DF}.Dockerfile
    image: client-${CLIENT_DF}
    links:
      - server
    environment:
      - URI=https://server:5001
      - CLIENT_ARGS=${CLIENT_ARGS}
      - CLIENT_ITERS=${CLIENT_ITERS}
      - NET_EVENT_LISTENER=${NET_EVENT_LISTENER}
      - CLR_OPENSSL_VERSION_OVERRIDE=${FORCE_OPENSSL_VERSION}

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    image: server-ubuntu-22
    ports:
      - "5001:5001"
    environment:
      - URLS=https://0.0.0.0:5001
